package com.goodcrypto.crypto;

/**
 * This version of com.goodcrypto.crypto plugin switches between 
 * implementions of CORBA, if any.
 *
 * All but one of the options below should be commented out.
 *
 * <p>Copyright 2002-2004 GoodCrypto Derived from Sun example code.
 * <br>Last modified: 2007.03.25
 *
 * @author GoodCrypto
 * @version 0.1
 */
public abstract class AbstractRedirectableCryptoService

// only one of the following options should be used 

// option for java code without CORBA
implements CryptoService
    
// option for java code generated by Sun's idlj
// implements com.goodcrypto.crypto.corba.CryptoPluginOperations
    
// option for java code generated by OpenORB's IDLCompiler
// extends com.goodcrypto.crypto.corba.CryptoPluginPOA

{
}

